spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dodal
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
  redis:
    host: localhost
    port: 6379

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  sql:
    init:
      mode: always
      encoding: utf-8
      platform: mysql
server:
  url: http://localhost:8080

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
